name: "reportlog tests"
on:
  push:
    branches: [main]
  workflow_dispatch:


jobs:
  ci:
    name: CI to test the reportlog action

    matrix:
      os: ["ubuntu-latest", "windows-latest", "macos-latest"]

    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false

    steps:
      - name: clone the repository
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: pip
      - name: install dependencies
        run: |
          pip install pytest pytest-reportlog
      - name: run the tests
        run: |
          pytest --report-log=pytest-log.jsonl
      - name: generate the report
        if: failure()
        uses: xarray-contrib/issue-from-pytest-log@main
        with:
          log-path: pytest-log.jsonl
          issue-title: "⚠️ Nightly upstream-dev CI: ${{matrix.os}} failed ⚠️"
