name: "reportlog tests"
on:
  push:
    branches: [main]
  workflow_dispatch:


jobs:
  ci:
    name: CI to test the reportlog action

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]

    runs-on: ${{matrix.os}}

    steps:
      - name: clone the repository
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - name: install dependencies
        run: |
          pip install pytest pytest-reportlog
      - name: run the tests
        run: |
          pytest --report-log=pytest-log.jsonl
      - name: generate the report
        if: failure()
        uses: keewis/issue-from-pytest-log@query-by-title
        with:
          log-path: pytest-log.jsonl
          issue-title: "CI: ${{matrix.os}} failed"
